# test my api


##### home page
GET http://127.0.0.1:5000

##### get all students
GET http://127.0.0.1:5000/students?page=2&limit=3

##### get student by id
GET http://127.0.0.1:5000/students/1

##### add a new student
POST http://127.0.0.1:5000/students
Content-Type: application/json

{
    "id": 22,
    "name": "Jake Doe",
    "email": "jake.doe@example.com",
    "age": 25,
    "gender": "male"
}

##### get student by id to verify addition
GET http://127.0.0.1:5000/students/22

##### update student by id
PUT http://127.0.0.1:5000/students/22
Content-Type: application/json

{
    "age": 26,
    "name": "soufiane amabraa"
}